services:
  
  sqlserver-evs:
    container_name: sqlserver-evs
    hostname: sqlserver-evs
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sql@Master
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S sqlserver-evs -U sa -P sql@Master -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - minha-rede
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  evsweb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver-evs;Database=evsdb02;User Id=sa;Password=sql@Master;Encrypt=False;TrustServerCertificate=True
      - ConnectionStrings__DbContext=Server=sqlserver-evs;Database=evsdb02;User Id=sa;Password=sql@Master;Encrypt=False;TrustServerCertificate=True
      
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
    depends_on:
      - sqlserver-evs #:
        #condition: service_healthy

    networks:
      - minha-rede
    restart: unless-stopped


networks:
  minha-rede:
    driver: bridge
      
volumes:
  sql-data:
  prometheus-data:
  grafana-data: