services:
  sqlserver-evs:
    image: mcr.microsoft.com/mssql/server:2022-latest

  evsweb.api:
    image: ${DOCKER_REGISTRY-}evswebapi
    build:
      context: .
      dockerfile: EVSWeb.Api/Dockerfile